version: '3.3'
services:
  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    # network_mode: host    # to allow DLNA feature
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    volumes:
      - '~/homelab/data/torrserver/CACHE:/opt/ts/torrents'
      - '~/homelab/data/torrserver/CONFIG:/opt/ts/config'
    ports:
      - '5665:5665'
    restart: unless-stopped
